"""Ethical Audit routes — PASSIONIT/PRUTL compliance reports."""
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from database import get_db
from models import RoleSuggestion, EthicalAudit, Employee
from schemas import AuditRequest, AuditReport, AuditDimension
from engine.ethics import score_passionit, score_prutl, compute_overall_ethics

router = APIRouter(prefix="/api", tags=["audit"])


@router.post("/ethical-audit", response_model=AuditReport)
def run_ethical_audit(req: AuditRequest, db: Session = Depends(get_db)):
    suggestion = db.query(RoleSuggestion).filter(RoleSuggestion.id == req.suggestion_id).first()
    if not suggestion:
        raise HTTPException(status_code=404, detail="Role suggestion not found")

    emp = db.query(Employee).filter(Employee.id == suggestion.employee_id).first()
    if not emp:
        raise HTTPException(status_code=404, detail="Employee not found")

    failure_count = len(emp.failure_events)
    has_explanation = bool(suggestion.explanation)

    # Run ethical scoring
    passionit = score_passionit(
        match_score=suggestion.match_score,
        resilience_index=suggestion.resilience_index,
        has_explanation=has_explanation,
        failure_count=failure_count,
    )
    prutl = score_prutl(
        match_score=suggestion.match_score,
        has_explanation=has_explanation,
    )

    overall_score, overall_risk = compute_overall_ethics(passionit, prutl)

    # Persist audit records
    for dim in passionit:
        db.add(EthicalAudit(
            suggestion_id=suggestion.id,
            framework="PASSIONIT",
            dimension=dim["dimension"],
            score=dim["score"],
            risk_level=dim["risk_level"],
            notes=dim["notes"],
        ))
    for dim in prutl:
        db.add(EthicalAudit(
            suggestion_id=suggestion.id,
            framework="PRUTL",
            dimension=dim["dimension"],
            score=dim["score"],
            risk_level=dim["risk_level"],
            notes=dim["notes"],
        ))
    db.commit()

    return AuditReport(
        suggestion_id=suggestion.id,
        employee_name=emp.name,
        suggested_role=suggestion.suggested_role,
        passionit=[AuditDimension(**d) for d in passionit],
        prutl=[AuditDimension(**d) for d in prutl],
        overall_risk=overall_risk,
        overall_score=overall_score,
        disclaimer=(
            "This ethical audit is generated by a rule-based compliance engine. "
            "In production, this should be supplemented with human ethical review "
            "and external bias testing (e.g., AIF360). No demographic data was "
            "used in the analysis pipeline."
        ),
    )


@router.get("/suggestions")
def list_suggestions(db: Session = Depends(get_db)):
    """List all role suggestions with employee info."""
    suggestions = db.query(RoleSuggestion).order_by(RoleSuggestion.created_at.desc()).all()
    results = []
    for s in suggestions:
        emp = db.query(Employee).filter(Employee.id == s.employee_id).first()
        results.append({
            "id": s.id,
            "employee_id": s.employee_id,
            "employee_name": emp.name if emp else "Unknown",
            "suggested_role": s.suggested_role,
            "match_score": s.match_score,
            "failure_score": s.failure_score,
            "resilience_index": s.resilience_index,
            "leadership_score": s.leadership_score,
            "growth_trajectory": s.growth_trajectory,
            "explanation": s.explanation,
            "created_at": s.created_at.isoformat() if s.created_at else None,
        })
    return results
