import { NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import { scorePassionit, scorePrutl, computeOverallEthics } from "@/lib/engine/ethics";

export async function POST(req: Request) {
  let body: { suggestion_id?: number };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ detail: "Invalid JSON" }, { status: 400 });
  }
  const suggestionId = Number(body.suggestion_id);
  if (!Number.isFinite(suggestionId)) {
    return NextResponse.json({ detail: "suggestion_id required" }, { status: 400 });
  }

  const suggestion = await prisma.roleSuggestion.findUnique({
    where: { id: suggestionId },
    include: { employee: { include: { failureEvents: true } } },
  });
  if (!suggestion || !suggestion.employee) {
    return NextResponse.json({ detail: "Role suggestion not found" }, { status: 404 });
  }

  const failureCount = suggestion.employee.failureEvents.length;
  const hasExplanation = Boolean(suggestion.explanation);

  const passionit = scorePassionit(
    suggestion.matchScore,
    suggestion.resilienceIndex,
    hasExplanation,
    failureCount,
  );
  const prutl = scorePrutl(suggestion.matchScore, hasExplanation);

  const { overall_score, overall_risk } = computeOverallEthics(passionit, prutl);

  await prisma.ethicalAudit.createMany({
    data: [
      ...passionit.map((d) => ({
        suggestionId: suggestion.id,
        framework: "PASSIONIT",
        dimension: d.dimension,
        score: d.score,
        riskLevel: d.risk_level,
        notes: d.notes,
      })),
      ...prutl.map((d) => ({
        suggestionId: suggestion.id,
        framework: "PRUTL",
        dimension: d.dimension,
        score: d.score,
        riskLevel: d.risk_level,
        notes: d.notes,
      })),
    ],
  });

  return NextResponse.json({
    suggestion_id: suggestion.id,
    employee_name: suggestion.employee.name,
    suggested_role: suggestion.suggestedRole,
    passionit,
    prutl,
    overall_risk,
    overall_score,
    disclaimer:
      "This ethical audit is generated by a rule-based compliance engine. " +
      "In production, this should be supplemented with human ethical review " +
      "and external bias testing (e.g., AIF360). No demographic data was " +
      "used in the analysis pipeline.",
  });
}
